### ISSUE TITLE
feature : 프롬프트 페이지 react-hook-form로 폼 관리, api 연결

### ISSUE THREAD

**Issue by yui880** [SW-rocket-dan/card-capture-fe#29]
### 📝 설명
- 퍼블리싱이 되어있는 프롬프트 페이지에 로직 연결

### 📌 TODO
- [x] `PromptInput` - Input 최상단 컴포넌트에 useForm 설정하고, 데이터와 핸들러 자식에게 넘겨주기
- [x] 자식 컴포넌트에서 input과 form 연결
- [ ] `PromptTextInput` - 문구 강조하는 버튼과, 강조된 문구 따로 저장하는 기능 구현
- [x] `PromptPreview` - 입력된 문구와 색상들이 화면에 띄워지도록 구현
- [x] api 요청 후 에디터 페이지로 이동

### 😎 추가 정보
- 색상 추천 api는 현재 없는것으로 추정. 백엔드에 요청하기
- 모달 반응형도 적용하기 -> 혹은 밑에 뜨도록 구현
