### ISSUE TITLE
feature : 에디터 json 데이터 확인 기능, build 오류 수정

### ISSUE THREAD

**Issue by yui880** [SW-rocket-dan/card-capture-fe#31]
## 📝 설명
- 배포하기 전 필요한 기능들을 구현하고, 오류들을 수정해서 배포할 것임

## 📌 TODO
- [x] json 데이터 넣으면 에디터 화면에서 어떻게 보여지는지 확인하기 위한 버튼 제공
   - 백엔드에서 ai로 json 데이터 만들고 나서 어떻게 보이는지 확인할 수 있도록 하기 위함 
- [x] ssr 오류 수정
   - build하면 ssr 오류가 나서 csr로 렌더링 되도록 수정
- [x] 템플릿 가져오는 api mock으로 대체
   - api 요청시 토큰이 필요하기도 하고, 임시 데이터가 보일 예정이라 임시 데이터 만들어야 함  
- [x] 안되는 기능 / 필요없는 기능 빼기

### 🗂️ 추가 정보
- 첫 배포 화이팅!
