### ISSUE TITLE
feature : 카드 이미지 export하기, 요소 delete 기능 추가

### ISSUE THREAD

**Issue by yui880** [SW-rocket-dan/card-capture-fe#35]
### 📝 설명
- html2canvas를 사용해서 dom에 그려진 요소들을 이미지로 export하고, 에디터 추가적으로 수정하기

### 📌 TODO
- [x] html2canvas 설치
- [x] EdtingArea에 그려진 카드 이미지로 다운로드 가능하게 하기
- [x] 요소 delete 기능 만들기, 요소 삭제 버튼 추가하기
- [x] 에디터 안되는 부분 disable / 가려놓기
- [ ] (가능하면) 에디터 드래그 오류 수정하기

### 🗂️ 추가 정보
- 자잘하게 수정할 부분이 많아서 해당 이슈에 들어갈 수 있음
