### ISSUE TITLE
feature : 에디터 오류 수정, UX 개선 

### ISSUE THREAD

**Issue by yui880** [SW-rocket-dan/card-capture-fe#39]
## 📝 설명
- 에디터 화면의 오류와 UX 개선을 위한 추가 개발 진행

## 📌 TODO
- [x] 에디터 드래그 기능 수정하기 - 클릭하지 않고도 드래그 가능하도록
- [x] 텍스트 박스 드래그 이후에 편집 상태로 들어가지 않고 계속 이동 가능하도록 수정
- [x] focusBox border로 인해 조금씩 이동되는 현상 수정
- [x] 에디터 나머지 탭에 beta라 안된다는 내용 띄우기
- [x] 도형 dropdown 만들기
- [x] 일러스트 api 연결하기
- [x] 색상 dropdown 가려지는 문제 해결하기
- [x] focusBox의 gap 문제 해결하기
- [x] sizeBox를 공유하면서 다른 요소 탭에서 size가 보이는 문제 수정
- [x] 현재 클릭한 요소가 아니면 탭이 안열리게 구현 - (고민)

### 🗂️ 추가 정보
- prompt와 main 화면의 오류도 추가적으로 수정될 수 있음
