### ISSUE TITLE
feature : 로그인 refresh token 처리, 마이페이지 구현

### ISSUE THREAD

**Issue by yui880** [SW-rocket-dan/card-capture-fe#41]
## 📝 설명
- refresh token 사용하여 자동 로그인 구현, 마이페이지에서 내 템플릿 모아보기 가능하게 하기

## 📌 TODO
- [x] refresh token 쿠키에 저장하고, access token 만료시 재발급하는 기능 구현
- [x] 마이페이지 간단하게 구현 후 내 템플릿 모아보기 api 연결
- [x] 에디터 텍스트 반영 안되는 오류 수정하기
- [ ] 메인화면 cs 받는 곳 만들기

### 🗂️ 추가 정보
- 없음
