### ISSUE TITLE
feature : ai 템플릿 생성 api 연결하기, 템플릿 수정본 서버에 저장

### ISSUE THREAD

**Issue by yui880** [SW-rocket-dan/card-capture-fe#45]
## 📝 설명
- ai를 사용해서 템플릿 생성하는 api를 연결하고, 에디터에서 템플릿 수정시에 서버에 저장하는 로직 구현

## 📌 TODO
- [ ] 템플릿 생성 ai api 연결 (이미 구현되어 있음, 주석처리 해제)
- [ ] 에디터에 결과물이 제대로 출력되는지 확인 후 오류 수정
- [ ] 템플릿 데이터 변경시 서버에 저장하는 api 호출
- 기타
   - [ ] 모바일 결제 오류 수정
   - [ ] 남은 무료 제작 개수 보기
   - [ ] 로딩 페이지 띄우기
   - [ ] 템플릿 가져오는 로직 react-query로 변경
   - [ ] footer 만들기 

### 🗂️ 추가 정보
- 오늘은 진짜 그랜드 오픈 해야지
