### ISSUE TITLE
feature : 결제 UX 개선, 남은 이용권 개수 확인 기능 추가

### ISSUE THREAD

**Issue by yui880** [SW-rocket-dan/card-capture-fe#47]
## 📝 설명
- 결제 UX를 개선하여 여러번 결제하거나 오류가 발생했을때 적절하게 처리가 되게 하고, 남은 이용권 개수 확인할 수 있게 업데이트

## 📌 TODO
- [ ] 남은 이용권 개수 보기 퍼블리싱
- [ ] 개인정보 처리방침 페이지 퍼블리싱
- [ ] 결제 완료시에 남은 이용권 개수 업데이트 되도록 변경
- [ ] 결제시 200일 때만 결제 되도록 수정
- [ ] 템플릿 생성 전 이용권 차감 안내 메세지 띄우기 / 결제 페이지 새창 띄우기 
- [ ] 템플릿 업데이트 주기 3초로 변경하기

### 🗂️ 추가 정보
- 진짜 그랜드 오픈 제발좀
